# **HELLO SIR, THIS IS MY PROJECT 1**

# **IMPORTING LIBRARIES**

In [ ]:
import numpy as np
import pandas as pd

data1 = pd.read_csv("/content/Data-cleaning-for-beginners-using-pandas.csv")     #'pd.read used for loading data'

data1.head() #to extract 1st 5 elements of the data

   Index   Age     Salary  Rating       Location  Established Easy Apply
0      0  44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      1  66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2      2   NaN  $77k-$89k    -1.0    New York,Ny           -1         -1
3      3  64.0  $44k-$99k     4.4       India In         1988         -1
4      4  25.0  $44k-$99k     6.4  Australia Aus         2002         -1

In [ ]:
data1.tail() #to extract last 5 elements of the data

    Index   Age     Salary  Rating       Location  Established Easy Apply
24     24  13.0  $44k-$99k    -1.0    New York,Ny         1987         -1
25     25  55.0  $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   NaN  $55k-$66k     NaN       India,In         1934       TRUE
27     27  52.0  $44k-$99k     5.4       India,In         1935         -1
28     28   NaN  $39k-$88k     3.4  Australia Aus         1932         -1

In [ ]:
data1.sample(3) #to extract any random elements of the data

    Index   Age     Salary  Rating       Location  Established Easy Apply
23     23   NaN  $44k-$99k     2.4    New York,Ny         1999       TRUE
26     26   NaN  $55k-$66k     NaN       India,In         1934       TRUE
7       7  44.0  $44k-$99k    -1.0  Australia Aus           -1         -1

In [ ]:
data1.shape #information about the data of how many rows and columns

(29, 7)

In [ ]:
data1.info() #gives info about each column (NULL valued and data types)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Index        29 non-null     int64
 1   Age          22 non-null     float64
 2   Salary       29 non-null     object
 3   Rating       28 non-null     float64
 4   Location     29 non-null     object
 5   Established  29 non-null     int64
 6   Easy Apply   29 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.7+ KB

In [ ]:
data1.isna().sum()  #will give count of missing values in each particular row of the dataset

Index          0
Age            7
Salary         0
Rating         1
Location       0
Established    0
Easy Apply     0
dtype: int64

In [ ]:
data1.columns  #to access all the columns

Index(['Index', 'Age', 'Salary', 'Rating', 'Location', 'Established',
       'Easy Apply'],
      dtype='object')

# **FIXED COLUMN NAMES**

In [ ]:
#fixed column names
data1.columns = data1.columns.str.lower().str.replace(' ', '_')   #data1.columns.str.lower() converts names of the column in lower case, using str.replace() also permits to replace the space in "easy apply to be replaced with an underscore"
print(data1.columns)

Index(['index', 'age', 'salary', 'rating', 'location', 'established',
       'easy_apply'],
      dtype='object')

# **AGE COLUMN**

In [ ]:
#Age Column
data1['age']  #to compare clean Age column

0     44.0
1     66.0
2      NaN
3     64.0
4     25.0
5     44.0
6     21.0
7     44.0
8     35.0
9     22.0
10    55.0
11    44.0
12     NaN
13    25.0
14    66.0
15    44.0
16    19.0
17     NaN
18    35.0
19    32.0
20     NaN
21    35.0
22    19.0
23     NaN
24    13.0
25    55.0
26     NaN
27    52.0
28     NaN
Name: age, dtype: float64

In [1]:
average_age = data1.age.mean()
print (average_age)

NameError: name 'data1' is not defined

In [ ]:
#Fix age Column
data1['age'] = data1['age'].fillna(average_age)   #fillna() functions allows us to fill the null values with the average value & update the original dataset with these values
data1['age'] = data1['age'].round(decimals=1)     #rounding off the values
data1['age']

0     44.0
1     66.0
2     39.0
3     64.0
4     25.0
5     44.0
6     21.0
7     44.0
8     35.0
9     22.0
10    55.0
11    44.0
12    39.0
13    25.0
14    66.0
15    44.0
16    19.0
17    39.0
18    35.0
19    32.0
20    39.0
21    35.0
22    19.0
23    39.0
24    13.0
25    55.0
26    39.0
27    52.0
28    39.0
Name: age, dtype: float64

In [ ]:
data1['age'].isna().sum()

0

# **SALARY COLUMN**

In [ ]:
data1['salary'] = data1['salary'].apply(lambda x:x.replace('$', ''))
data1['salary'] = data1['salary'].apply(lambda x:x.replace('k', ''))
print(data1['salary'])

0      44-99
1      55-66
2      77-89
3      44-99
4      44-99
5      77-89
6      44-99
7      44-99
8      44-99
9      44-99
10     10-49
11     10-49
12     44-99
13     44-99
14     44-99
15    88-101
16     19-40
17     44-99
18     44-99
19     44-99
20     44-99
21     44-99
22     55-66
23     44-99
24     44-99
25     44-99
26     55-66
27     44-99
28     39-88
Name: salary, dtype: object

In [ ]:
data1.head()

   index   age salary  rating       location  established easy_apply
0      0  44.0  44-99     5.4       India,In         1999       TRUE
1      1  66.0  55-66     3.5    New York,Ny         2002       TRUE
2      2  39.0  77-89    -1.0    New York,Ny           -1         -1
3      3  64.0  44-99     4.4       India In         1988         -1
4      4  25.0  44-99     6.4  Australia Aus         2002         -1

**Changed data type of the age column to 'int'**

In [ ]:
data1['age'] = data1['age'].astype(int)
print(data1['age'])

0     44
1     66
2     39
3     64
4     25
5     44
6     21
7     44
8     35
9     22
10    55
11    44
12    39
13    25
14    66
15    44
16    19
17    39
18    35
19    32
20    39
21    35
22    19
23    39
24    13
25    55
26    39
27    52
28    39
Name: age, dtype: int64

# **ESTABILISHED COLUMN**

In [ ]:
#Clean Estabilished Column
data1['established'] = data1['established'].replace(-1,np.nan)
data1['established'].fillna('Unknown',inplace=True)
print(data1['established'])

0      1999.0
1      2002.0
2     Unknown
3      1988.0
4      2002.0
5      1999.0
6     Unknown
7     Unknown
8     Unknown
9     Unknown
10     2008.0
11     2009.0
12     1999.0
13     2019.0
14     2020.0
15     1999.0
16     1984.0
17     1943.0
18     1954.0
19     1955.0
20     1944.0
21     1946.0
22     1988.0
23     1999.0
24     1987.0
25     1980.0
26     1934.0
27     1935.0
28     1932.0
Name: established, dtype: object

# **LOCATION COLUMN**

In [ ]:
#Location Column
data1['location'] = data1.location.astype

In [ ]:
#Cleaning the location column and splitting the city from the city short name

data1['location'] = data1['location'].str.replace("Australia Aus", "Australia, Aus")
data1['location_city'] = data1['location'].str.split(",", expand=True).get(0)
data1['city_sign'] = data1['location'].str.split(",", expand=True).get(1)
data1.drop('location', inplace=True, axis=1)

AttributeError: Can only use .str accessor with string values!

# **RATING COLUMN**

In [ ]:
#Rating Column
#Cleaning the RAting Column and replacing special characters with Nan Values
data1['rating'] = data1["rating"].replace(-1,np.nan)

#Now replace those nan values with the ratind mean()
data1['rating'] = data1["rating"].fillna(data1['rating'].mean()).round(decimals=1)

print(data1['rating'])

0     5.4
1     3.5
2     4.3
3     4.4
4     6.4
5     1.4
6     0.0
7     4.3
8     5.4
9     7.7
10    5.4
11    6.7
12    0.0
13    4.3
14    4.0
15    3.0
16    4.5
17    5.3
18    6.7
19    3.3
20    5.7
21    5.0
22    7.8
23    2.4
24    4.3
25    0.0
26    4.3
27    5.4
28    3.4
Name: rating, dtype: float64

# **EASY APPLY COLUMN**

In [ ]:
#Cleaning the easy_apply
data1['easy_apply'] = data1['easy_apply'].replace("-1", "True")
print(data1['easy_apply'])

0     TRUE
1     TRUE
2     True
3     True
4     True
5     TRUE
6     True
7     True
8     True
9     TRUE
10    TRUE
11    True
12    True
13    TRUE
14    TRUE
15    True
16    True
17    TRUE
18    TRUE
19    TRUE
20    TRUE
21    True
22    TRUE
23    TRUE
24    True
25    TRUE
26    TRUE
27    True
28    True
Name: easy_apply, dtype: object

# **FINAL RESULT**

In [ ]:
#Final Result
data1.head()

   index  age salary  rating  location established easy_apply
0      0   44  44-99     5.4       NaN      1999.0       TRUE
1      1   66  55-66     3.5       NaN      2002.0       TRUE
2      2   39  77-89     4.3       NaN     Unknown       True
3      3   64  44-99     4.4       NaN      1988.0       True
4      4   25  44-99     6.4       NaN      2002.0       True

# ***FROM HERE PROJECT 2 STARTS***

# **IMPORTING LIBRARIES**

In [ ]:
import numpy as np  #Linear Algebra
import panda as pd  #Data processing

# **UPLOADING THE CONVERTED CSV FILE**

In [ ]:
data2 = pd.read_csv("/content/Chitople CSV.csv")

In [ ]:
data2.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [ ]:
data2.tail()

,order_id,quantity,item_name,choice_description,item_price
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
data2.shape

(4622, 5)

In [ ]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   float64
 1   quantity            4622 non-null   float64
 2   item_name           54 non-null     float64
 3   choice_description  0 non-null      float64
 4   item_price          4622 non-null   float64
dtypes: float64(5)
memory usage: 180.7 KB

In [ ]:
data2.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

# **TURN 'item_price' INTO FLOAT**

In [ ]:
#Turn the item_price into float
data2['item_price'] = data2['item_price'].replace('\D', '', regex=True)
data2['item_price'] = data2['item_price'].replace('', np.nan)  #Replace empty strings
data2['item_price'] = data2['item_price'].astype(float)
print(data2['item_price'])

0        239.0
1        339.0
2        339.0
3        239.0
4       1698.0
         ...
4617    1175.0
4618    1175.0
4619    1125.0
4620     875.0
4621     875.0
Name: item_price, Length: 4622, dtype: float64

# **Quantity of each item**

In [ ]:
#Quantity of Each item
item_quantities = data2['item_name'].value_counts().reset_index()
item_quantities.columns = ['item_name', 'quantity']
print(item_quantities)

   item_name  quantity
0        6.0        54

# **What was the most ordered item in the choice_description column?**

In [ ]:
#What was the most ordered item in choice descrption column
choice_description_column = data2['choice_description']

if not choice_description_column.dropna().empty:
  most_ordered_item = choice_description_column.dropna().value_counts().idxmax()
  print("The most ordered item is : ", most_ordered_item)

else:
  print("No null-values in the 'choice_description column.")

No null-values in the 'choice_description column.

# **How many items were ordered in total?**

In [ ]:
#How many items were ordered in total
total_ordered_items = data2['quantity'].sum()

print("Total number of items ordered:", total_ordered_items)

Total number of items ordered: 4972.0

# **How much was the revenue for the period in the dataset?**

In [ ]:
#How much was the revenue for the period in the data set?
# Clean the 'item_price' column and convert it to a numeric type
data2['item_price'] = data2['item_price'].replace('[\$,]', '', regex=True).astype(float)

# Calculate the revenue by multiplying quantity and item price, then summing the results
total_revenue = (data2['quantity'] * data2['item_price']).sum()

print("Total revenue for the period:", total_revenue)

Total revenue for the period: 3923702.0

# **How many orders were made in the period?**

In [ ]:
#How many orders were made in the period?
total_orders = data2['order_id'].nunique()

print("Total number of orders made in the period:", total_orders)

Total number of orders made in the period: 1834

# **What is the average revenue amount per order?**

In [ ]:
# Calculate the average revenue per order
average_revenue_per_order = round(total_revenue / total_orders, 2)

print("Average revenue amount per order:", average_revenue_per_order)

Average revenue amount per order: 2139.42

# **How many different items are sold?**

In [ ]:
#Different items sold
different_items_sold = data2['item_name'].nunique()

print("Number of different items sold:", different_items_sold)

Number of different items sold: 1